server:
  port: 8087

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: ORDER-SERVICE
              uri: lb://ORDER-SERVICE
              predicates:
                - Path=/order-service/**
              filters:
                - StripPrefix=1

            - id: PAYMENT-SERVICE
              uri: lb://PAYMENT-SERVICE
              predicates:
                - Path=/payment-service/**
              filters:
                - StripPrefix=1

            - id: PRODUCT-SERVICE
              uri: lb://PRODUCT-SERVICE
              predicates:
                - Path=/product-service/**
              filters:
                - StripPrefix=1

            - id: USER-SERVICE
              uri: lb://USER-SERVICE
              predicates:
                - Path=/user-service/**,/auth/**
              filters:
                - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9090/eureka